name: Xiaomi R4A Build (New)

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag (e.g. v1.0.0)"
        required: true
        default: "v1.0.0"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 🧹 清理空间
      run: |
        sudo rm -rf /opt/*
        df -h

    - name: 📥 克隆当前仓库
      uses: actions/checkout@v3

    - name: 📦 获取 OpenWrt 源码
      run: |
        git clone --depth=1 https://github.com/openwrt/openwrt openwrt
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: ⚙️ 替换配置文件
      run: |
        cp new.config openwrt/.config

    - name: 🛠️ 编译固件
      run: |
        cd openwrt
        make defconfig
        make -j$(nproc) download
        make -j$(nproc)

    - name: 📦 打包固件为 ZIP
      run: |
        cd openwrt/bin/targets/
        zip -r firmware.zip ./

    - name: 🚀 发布到 GitHub Releases
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.event.inputs.tag }}
        name: Xiaomi R4A Firmware ${{ github.event.inputs.tag }}
        body: |
          自动编译的小米 4A 千兆版固件。
          配置文件：new.config
          构建时间：${{ github.run_id }}
      files: |
        openwrt/bin/targets/firmware.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
